version: '3.8'

services:
  backend:
    build:
      context: ./backend 
    container_name: laravel_app
    restart: unless-stopped
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:Mc33zetJFUQe3LaXtCNHJkz095iPIUshGbEfh52cDEs=
      - APP_URL=http://localhost
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=developers
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - ./backend:/var/www/html  
    ports:
      - "8000:80"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend  
    container_name: react_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: developers
    ports:
      - "3307:3306"  # Alterando a porta mapeada no host para 3307
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
